"""add_forensic_models

Revision ID: b05fe0aef822
Revises: 
Create Date: 2026-01-16 00:51:13.178950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b05fe0aef822'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('constituency', sa.String(length=100), nullable=False),
    sa.Column('contractor_name', sa.String(length=255), nullable=False, comment='Indexed for tracking bad actors across projects'),
    sa.Column('total_budget', sa.Numeric(precision=15, scale=2), nullable=False, comment='Supports up to 999 billion KES'),
    sa.Column('status', postgresql.ENUM('PLANNED', 'ACTIVE', 'COMPLETED', 'STALLED', 'FLAGGED', name='project_status'), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False, comment='AI-computed score 0-100'),
    sa.Column('risk_level', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_contractor_name'), 'projects', ['contractor_name'], unique=False)
    op.create_index('ix_projects_county_status', 'projects', ['county', 'status'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Raw AI Crime Scene analysis output'),
    sa.Column('flagged_anomalies', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="e.g., ['Price Inflation', 'Ghost Material', 'Phantom Upgrade']"),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash for blockchain verification'),
    sa.Column('doc_type', sa.String(length=50), nullable=False, comment='e.g., BoQ, Invoice, Contract, Photo'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=False),
    sa.Column('gps_lng', sa.Float(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('is_off_site', sa.Boolean(), nullable=False, comment='True if GPS does not match project location - potential fraud indicator'),
    sa.Column('status', postgresql.ENUM('PENDING', 'VERIFIED', 'REJECTED', name='verification_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_project_id'), 'verifications', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_project_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_project_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index('ix_projects_county_status', table_name='projects')
    op.drop_index(op.f('ix_projects_contractor_name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
